spring:
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp

  datasource:
    username: root
    password: johnty
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
