spring:
  application:
    name: user-service

  datasource:
    username: root
    password: johnty
    url: jdbc:mysql://localhost:3306/infy_go_user

server:
  servlet.context-path: /user-service
  port: 8100


logging:
  file: Errorlog.log
  level:
    root: info
    com.infoys.ars: info
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss,SSS} %5p [%t] %c [%M] - %m%n"




